/**
 * Generate Personalized Outreach for Lead
 *
 * Creates personalized email and call scripts based on the lead's
 * specific situation, website analysis, and industry.
 */

import { NextResponse } from 'next/server';
import { createAdminClient } from '@/utils/supabase/admin';
import type { WebsiteAnalysis, OutreachScript } from '@/types/database';

const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY;
const OPENROUTER_BASE_URL = 'https://openrouter.ai/api/v1';

interface AIResponse {
  choices: Array<{
    message: {
      content: string;
    };
  }>;
}

export async function POST(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const supabase = createAdminClient();
    const { id: leadId } = await params;
    const body = await request.json();
    const {
      industry,
      businessName,
      websiteAnalysis,
      previewUrl,
      contactName,
      projectId,
    } = body;

    if (!leadId) {
      return NextResponse.json({ error: 'Lead ID is required' }, { status: 400 });
    }

    // Generate personalized outreach
    const outreach = await generatePersonalizedOutreach({
      businessName,
      industry,
      websiteAnalysis,
      previewUrl,
      contactName,
    });

    if (!outreach) {
      return NextResponse.json(
        { error: 'Failed to generate outreach' },
        { status: 500 }
      );
    }

    // Update lead to mark outreach as generated
    await supabase
      .from('leads')
      .update({
        outreach_generated: true,
        updated_at: new Date().toISOString(),
      })
      .eq('id', leadId);

    // Save outreach to outreach artifact if project exists
    if (projectId) {
      const { data: existingArtifact } = await supabase
        .from('artifacts')
        .select('*')
        .eq('project_id', projectId)
        .eq('type', 'outreach')
        .single();

      // Transform outreach result to match OutreachScript type
      const outreachScript: OutreachScript = {
        leadId,
        leadName: businessName,
        emailScript: outreach.email,
        callScript: {
          opener: outreach.call.opener,
          valueProposition: outreach.call.valueProposition,
          questions: [], // Not generated by AI, empty for now
          objectionHandlers: outreach.call.objectionHandlers.reduce((acc, handler, idx) => {
            acc[`objection_${idx + 1}`] = handler;
            return acc;
          }, {} as Record<string, string>),
          closeAttempt: outreach.call.close,
        },
      };

      if (existingArtifact) {
        // Add to existing outreach artifact
        const existingData = existingArtifact.data;
        const scripts = existingData.scripts || [];

        // Remove any existing script for this lead
        const filteredScripts = scripts.filter((s: OutreachScript) => s.leadId !== leadId);
        filteredScripts.push(outreachScript);

        await supabase
          .from('artifacts')
          .update({
            data: { ...existingData, scripts: filteredScripts },
            updated_at: new Date().toISOString(),
          })
          .eq('id', existingArtifact.id);
      } else {
        // Create new outreach artifact
        await supabase.from('artifacts').insert({
          project_id: projectId,
          type: 'outreach',
          data: {
            scripts: [outreachScript],
            tone: 'professional',
            useCase: 'website_services',
          },
          version: 1,
        });
      }
    }

    return NextResponse.json({
      success: true,
      outreach,
    });
  } catch (error) {
    console.error('[GenerateOutreach] Error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

interface OutreachParams {
  businessName: string;
  industry: string;
  websiteAnalysis?: WebsiteAnalysis;
  previewUrl?: string;
  contactName?: string;
}

interface OutreachResult {
  email: {
    subject: string;
    body: string;
    followUp1: string;
    followUp2: string;
  };
  call: {
    opener: string;
    valueProposition: string;
    objectionHandlers: string[];
    close: string;
  };
  dm: {
    initial: string;
    followUp: string;
  };
}

async function generatePersonalizedOutreach(
  params: OutreachParams
): Promise<OutreachResult | null> {
  const { businessName, industry, websiteAnalysis, previewUrl, contactName } = params;

  // Build context for AI
  const websiteContext = buildWebsiteContext(websiteAnalysis);

  const prompt = `Generate personalized outreach scripts for a potential web design/development client.

TARGET BUSINESS:
- Business Name: ${businessName}
- Industry: ${industry}
- Contact Name: ${contactName || 'Business Owner'}
${websiteContext}
${previewUrl ? `- Preview Website URL: ${previewUrl}` : ''}

Generate compelling, personalized outreach that:
1. References specific issues/opportunities from their website analysis
2. Offers clear value based on their situation
3. Creates urgency without being pushy
4. Sounds human and conversational, not salesy
${previewUrl ? '5. Mentions the preview website we created for them' : ''}

Return a JSON object with this structure:
{
  "email": {
    "subject": "Short, personalized subject line",
    "body": "Main email body (150-200 words)",
    "followUp1": "First follow-up email (shorter, 100 words)",
    "followUp2": "Second follow-up / break-up email (brief, creates urgency)"
  },
  "call": {
    "opener": "Opening line when they answer",
    "valueProposition": "Your main pitch (30 seconds)",
    "objectionHandlers": ["Array of responses to common objections"],
    "close": "How to close the call and get next steps"
  },
  "dm": {
    "initial": "LinkedIn/social media DM (very short, conversational)",
    "followUp": "Follow-up DM if no response"
  }
}

Return ONLY the JSON object, no markdown or explanations.`;

  if (!OPENROUTER_API_KEY) {
    return generateFallbackOutreach(params);
  }

  try {
    const response = await fetch(`${OPENROUTER_BASE_URL}/chat/completions`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${OPENROUTER_API_KEY}`,
        'Content-Type': 'application/json',
        'HTTP-Referer': process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000',
      },
      body: JSON.stringify({
        model: 'anthropic/claude-sonnet-4',
        messages: [{ role: 'user', content: prompt }],
        temperature: 0.7,
        max_tokens: 4000,
      }),
    });

    if (!response.ok) {
      throw new Error(`OpenRouter API error: ${response.status}`);
    }

    const data: AIResponse = await response.json();
    const content = data.choices[0]?.message?.content;

    if (!content) {
      throw new Error('No content in AI response');
    }

    // Parse JSON
    let jsonContent = content;
    if (content.includes('```json')) {
      jsonContent = content.split('```json')[1].split('```')[0];
    } else if (content.includes('```')) {
      jsonContent = content.split('```')[1].split('```')[0];
    }

    return JSON.parse(jsonContent.trim());
  } catch (error) {
    console.error('[GenerateOutreach] AI generation failed:', error);
    return generateFallbackOutreach(params);
  }
}

function buildWebsiteContext(analysis?: WebsiteAnalysis): string {
  if (!analysis) {
    return '- Website Status: Unknown';
  }

  let context = `- Website Status: ${analysis.status.toUpperCase()}`;
  context += `\n- Opportunity Score: ${analysis.score}/100`;

  if (analysis.issues && analysis.issues.length > 0) {
    context += `\n- Key Issues:`;
    analysis.issues.slice(0, 5).forEach((issue) => {
      context += `\n  • ${issue}`;
    });
  }

  if (analysis.hasSSL === false) {
    context += '\n- Missing SSL certificate (security concern)';
  }

  if (analysis.mobileResponsive === false) {
    context += '\n- Not mobile-responsive (losing mobile customers)';
  }

  if (analysis.loadTime && analysis.loadTime > 5000) {
    context += `\n- Slow load time: ${(analysis.loadTime / 1000).toFixed(1)}s`;
  }

  return context;
}

function generateFallbackOutreach(params: OutreachParams): OutreachResult {
  const { businessName, industry, websiteAnalysis, previewUrl, contactName } = params;
  const name = contactName || 'there';

  const hasNoWebsite = websiteAnalysis?.status === 'none';
  const hasBrokenWebsite = websiteAnalysis?.status === 'broken';
  const hasOutdatedWebsite = websiteAnalysis?.status === 'outdated' || websiteAnalysis?.status === 'poor';

  let painPoint = 'improve your online presence';
  let urgency = 'customers are searching online for businesses like yours';

  if (hasNoWebsite) {
    painPoint = 'get your business online';
    urgency = "you're invisible to customers searching online";
  } else if (hasBrokenWebsite) {
    painPoint = 'fix your website issues';
    urgency = 'your current website is turning away potential customers';
  } else if (hasOutdatedWebsite) {
    painPoint = 'modernize your website';
    urgency = 'an outdated website makes your business look dated';
  }

  return {
    email: {
      subject: `Quick question about ${businessName}'s website`,
      body: `Hi ${name},

I was researching ${industry} businesses in your area and came across ${businessName}. I noticed you might benefit from a stronger online presence${websiteAnalysis?.issues?.[0] ? ` - specifically, ${websiteAnalysis.issues[0].toLowerCase()}` : ''}.

I specialize in helping ${industry} businesses ${painPoint}. In fact, ${urgency}.

${previewUrl ? `I actually put together a quick preview of what a modern website could look like for ${businessName}: ${previewUrl}` : "I'd love to show you a free mockup of what an updated website could look like."}

Would you be open to a quick 15-minute call this week to discuss?

Best,
[Your Name]`,
      followUp1: `Hi ${name},

Just following up on my email about ${businessName}'s website. ${previewUrl ? `Did you get a chance to see the preview I created?` : "I'd still love to show you what a modern website could do for your business."}

No pressure - just let me know if you're interested in chatting.

[Your Name]`,
      followUp2: `Hi ${name},

Last email from me! I know you're busy running ${businessName}.

If a new website isn't a priority right now, no worries at all. But if you ever want to chat about ${painPoint}, I'm just a reply away.

Best of luck with everything!

[Your Name]`,
    },
    call: {
      opener: `Hi, is this ${name}? This is [Your Name]. I'm reaching out to ${industry} business owners about their online presence. Do you have just 2 minutes?`,
      valueProposition: `I specialize in helping ${industry} businesses like ${businessName} ${painPoint}. I noticed ${websiteAnalysis?.issues?.[0] || 'some opportunities to improve your online presence'}, and I wanted to offer a free assessment of what a modern website could do for your business. No obligation - just want to show you the possibilities.`,
      objectionHandlers: [
        '"I\'m happy with my current website" → "That\'s great! Out of curiosity, when was it last updated? I\'ve seen a lot of changes in what works online, especially for mobile users."',
        '"I don\'t have the budget" → "I totally understand. What if I showed you some options that could actually pay for themselves by bringing in new customers?"',
        '"I\'m too busy right now" → "I hear you - running a business is a lot. Would it help if I sent over a quick preview so you can look at it when you have time?"',
        '"Send me an email" → "Absolutely! What\'s the best email address? I\'ll include a preview of what your new website could look like."',
      ],
      close: `So here's what I'd like to do - let me put together a free mockup specifically for ${businessName}, no strings attached. You can see exactly what I'm talking about. What email should I send that to?`,
    },
    dm: {
      initial: `Hey ${name}! Saw ${businessName} online and thought your ${industry} business could really benefit from a stronger web presence. Would you be open to seeing a free mockup?`,
      followUp: `Just circling back - didn't want you to miss out on seeing what a modern website could do for ${businessName}. Let me know if you're interested!`,
    },
  };
}
